### ISSUE TITLE
[Ask] 

### ISSUE THREAD

**Issue by bhwqaq** [ittuann/Enterprise_E#3]
### Describe your question

我想问一下，在b站视频当中，通过导入数据，用matlab系统模式识别了一个2极点1零点的传递函数，然后再用这个传递函数，在matlab仿真当中仿真出了好的PID参数。但是在C语言文件当中这个过程是通过哪一个代码来实现的，或者是在你写的c语言中，pid的控制对象是什么，我理解的是：将采集的输入，输出数据拟合成传递函数过程用c语言表示出来，再用c语言表示pid控制这个传递函数，我也想请问一下你的pid控制过程

### System Info

```Shell
COde的c语言文件中哪一个是我询问问题的解答处
```

### Validations

- [X] Remember to follow the community guidelines and be friendly.

**Comment by ittuann** [comment]
不必次使用C语言来实现电机系统辨识和PID仿真的过程，只需直接将Matlab输出的系数应用于标准的增量式PID函数即可。至于问到的控制对象是什么，速度环PID的控制对象自然是电机。

如需更详细的信息，可以参考我之前的博客文章：
- [智能车常规 PID 以及改进式 PID](https://ittuann.github.io/2021/08/29/CarPID.html) 
- [智能车电机系统辨识和PID仿真自动调参](https://ittuann.github.io/2021/08/29/CarSimulate.html)

希望我的知识和分享能对你有所帮助~
