### ISSUE TITLE
[Ask] PID Tune

### ISSUE THREAD

**Issue by Alaye-Dong** [ittuann/Enterprise_E#4]
## 问题1 增量式PID中I的处理
>注意PID Tuner计算连续型时的积分项I需要乘上系统的采样时间（单位秒）才是常规位置式PID的参数

请问如果是增量式PID，得出的I还需要做乘上系统的采样时间或者其它的操作吗？
## 问题2 模块的实际选用类型
>（离散型其实应该使用的是Discrete PID Controller和Discrete Transfer Fcn

教程中选用的是普通的PID Controller和Transfer Fcn。对于现实调试智能车竞赛中电机来说，应该将Simulink建立的PID模型的模块换成Discrete PID Controller和Discrete Transfer Fcn才能得到更正确的结果？
## 问题3 `Time domain`离散和连续
对于智能车系统来说，通常是在定时中断中读取编码器和输出电机的PID，这样这个系统都是离散型的，那么在`Matlab PID Controller`中的`Time domain`是否可以直接选择`Discrete-time`离散型进行PID Tune？如果选择离散型，此时的`Sample time (-1 for inherited)：`如何正确设置，是设置为定时中断的时间吗？
![image](https://github.com/ittuann/Enterprise_E/assets/123649770/a097d2af-580c-4db8-8483-a33ddc0d284d)

### System Info

```Shell
STC32F单片机 F车模
```

### Additional context

看了大佬给出的教程，受益匪浅👍，但仍有一些问题，希望可以解答🥰

### Validations

- [X] Remember to follow the community guidelines and be friendly.

**Comment by ittuann** [comment]
关于问题1，Matlab的PID Tuner仅支持位置式PID的仿真。如果就想用增量式PID，需要自行推导一遍公式。

关于问题2和3，其实正如博客中所述，离散化是最准确的仿真方法。你的看法是正确的，单片机采样本质上是离散的，理论上电机的传递函数和PID控制都应采用离散而非连续的方式进行仿真。不过由于当时比赛时间有限，我未能来得及采用离散时间方法进行仿真测试。离散型仿真的配置时间即为采样时间。

这个Issues我会先标记为not planned。如果有还问题欢迎邮件联系我一起讨论~
